### ISSUE TITLE
CriteriaInterface never used

### ISSUE THREAD

**Issue by kamov** [Bosnadev/Repositories#104]
I would like to know for what it's used the CriteriaInterface?

In the article here: https://bosnadev.com/2015/03/07/using-repository-pattern-in-laravel-5/
your Criteria for film implement CriteriaInterface, however here in repository you mention to:

> Your criteria class MUST extend the abstract Bosnadev\Repositories\Criteria\Criteria class.

My doubts are also that for each class Criteria we can apply only 1 method. Can we have 1 single Criteria class for different methods?

**Comment by elceka** [comment]
CriteriaInterface is implemented by Repository abstract class, because this interface contain methods intended for Repository class, not for Criteria class.
