### ISSUE TITLE
Create method doesn't work

### ISSUE THREAD

**Issue by josvar** [Bosnadev/Repositories#15]
When I try to use the create method, it throws me :
BadMethodCallException in Builder.php line 1990: Call to undefined method Illuminate\Database\Query\Builder::create()

I think it's because the repository stores an instance of Illuminate \ Database \ Eloquent \ Builder instead  Illuminate \ Database \ Eloquent \ Model instance

**Comment by mirzap** [comment]
I think it should work now. Thanks.
