### ISSUE TITLE
How can we use other methods traditionally available in the model?

### ISSUE THREAD

**Issue by jadjoubran** [Bosnadev/Repositories#26]
Say I have this code:

    use App\Repositories\TestsRepo as Test;

    public function show($reference_number, Test $test){
    	return $shipment->findBy( 'reference_number', $reference_number );
    }

Now what if I need to apply other eloquent methods? Such as ->where('field', 'value'); or order_by
I know the order_by is not relevant in this example, but there are tons of other eloquent methods that I'm not able to chain.

Thanks!

**Comment by Sixsic7** [comment]
Be more specific + security

**Comment by jadjoubran** [comment]
What do you mean?

**Comment by stuarthannig** [comment]
Create a method named appropriately in your repository to do the Eloquent calls needed. The point of Repositories is the abstract Eloquent away from your app so you can easily drop in a replacement ORM and not be coupled to Eloquent, yadda yadda.

**Comment by jadjoubran** [comment]
Okay thanks!
I don't think I'll use this package then because I have some complex queries and the functions available here won't suffice.
Thanks again!

**Comment by stuarthannig** [comment]
Being that the Repository has all Eloquent functionality, it should be all that you need as an interface between your Controller and data source. Similar to using a facade to present data to your View layer.

**Comment by jadjoubran** [comment]
Noted, thanks again for your support!
