### ISSUE TITLE
update method not working

### ISSUE THREAD

**Issue by jdsingh** [Bosnadev/Repositories#27]
I'm using mongoDB as database and https://github.com/jenssegers/laravel-mongodb package.

When I run this code `$this->user->update($request->all(), $id);`, it executes fine but the data is not being updated in database.

Version info
"laravel/framework": "5.0.*",
"jenssegers/mongodb": "~2.1",

**Comment by RiCi12** [comment]
I can say the same thing: using sqlite (with default PDO and driver), update method does not acctualy affect data in the DB.

I'm using the  @dev version of the package, from packagist.

**Comment by stuarthannig** [comment]
I didn't try update with this package, but I wasn't seeing the results either when doing it from straight Elequent on MySQL. Might be related.

**Comment by RiCi12** [comment]
It could be. I've spent some time fixing the bug, however i wasn't able to
solve the problem, either with some proof-error code for laravel 4.2/5.0.
Maybe some bug introduced in recent laravel/symfony?
Il 11/mag/2015 18:46, "Stuart Hannig" <notifications@github.com> ha scritto:

**Comment by robertvrabel** [comment]
My problem is it is trying to update _method and _token in the DB since those are in the request object. Its not taking into account only the model's fields. Anyone also run into this issue?

**Comment by jdsingh** [comment]
@robertvrabel Did you try `$request->except('_method', '_token')` ?

**Comment by robertvrabel** [comment]
@jdsingh Yeah i did. I can get it to work doing that, but it seems like unnecessary overhead? I'd hate to have that lingering all over the place.

**Comment by jdsingh** [comment]
@robertvrabel yeah that looks bit dirty, it should work with model's fill-able property but still yours work with that.

I have to use this 
```php
$model = $this->model->find($id);
$model->update($request->all());
```

**Comment by jdsingh** [comment]
Got it working by specifying the primary key $attribute as mongodb uses "_id" as primary key.

```php
$this->user->update($request->all(), $id, "_id");
```
