### ISSUE TITLE
New branch - refactor

### ISSUE THREAD

**Issue by appkr** [Bosnadev/Repositories#33]
Hey! @Bosnadev

Last couple of days I've been playing around with your package and made some modification for my personal project. Since I made too much change to your package after forking (this includes api change, and this will break your users' code), I think pull request is not appropriate. But if you happen to like even a small part of my work, you can merge them. Thanks for the great package.

https://github.com/appkr/Repositories/tree/refactor

With best wishes,
Appkr.

**Comment by mirzap** [comment]
Hi, thank you. I'll check it,
