### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by JessNielsen** [Bosnadev/Repositories#4]
Hi, i would like to use your package, could you perhaps write something in the readme about how i can integrate it? it seems you extend eloquent and such but do you entirely discard eloquent models?

Thanks

**Comment by mirzap** [comment]
Hi, I'm working on it. It may take day or two, but for sure Reame file will be updated in the next few commits. Thanks ;)

**Comment by mirzap** [comment]
I've added some basic information how you can use this package. If you have any question feel free to ask.
