### ISSUE TITLE
How to create a model through repository

### ISSUE THREAD

**Issue by xcaptain** [Bosnadev/Repositories#41]
I don't want to use massive assignment, so the default create method doesn't work for me.

I tried to use the traditional way to save a model, but I can't assign attributes to a model because model is protected.
```php
$this->post->model->title = 'test'
$this->post->model->save();
```
just throw an error.

**Comment by xcaptain** [comment]
@mirzap How about add a method saveModel()? I can work on it.

**Comment by mirzap** [comment]
Please make a new PR, without composer.json changes (you can add your self as contributor, but don't remove my name)

**Comment by xcaptain** [comment]
commited again, hope it can be merged.
