### ISSUE TITLE
Unable Create Record With Beanstalkd Queue

### ISSUE THREAD

**Issue by ghprod** [Bosnadev/Repositories#65]
Hi

do you ever face problem that you cant insert/create any record when queue driver set as `beanstalkd` ?

i always got 

```
Trying to get property of non-object 
```

Seems like `$this->model` got undefined and error above got triggered when execute this line

```
return $this->model->create($data);
```

my code is pretty simple

```php
<?php

// controller
        $this->dispatch(
            new \Modules\Accounting\Jobs\HitungAdministrasiSimpanan('fa108a98-cd89-402e-b60f-bb1b039c2606')
        );

// job
        $transactionRepository = app()->make(TransactionRepository::class);

        // .. rest code ...

        $transactionRepository->create([
                'reference'   => 'SLUG',
                'nominal'     => 0,
                'description' => 'BLANK',
            ]);
```

But when queue driver back to `sync` then everything is ok ..

Any idea?

Thanks

**Comment by hananwm** [comment]
Hey, if you're using an up to date laravel then the create method in Illuminate\Database\Query is now called "insert", 
just change the method name in your repository abstract class and in your repository interface to insert instead of create.
then just call insert instead of create:
 $transactionRepository->insert([
                'reference'   => 'SLUG',
                'nominal'     => 0,
                'description' => 'BLANK',
            ]);

**Comment by ghprod** [comment]
ah my bad this is an old issue that already solved .. sorry for bothering you :)
