### ISSUE TITLE
Eager Loading

### ISSUE THREAD

**Issue by azooziidev** [Bosnadev/Repositories#71]
Are there any plans to extend this package to include the Eager Loading functionality in Repositories described here?

[https://bosnadev.com/2015/03/26/using-repository-pattern-in-laravel-5-eloquent-relations-and-eager-loading/]

Thanks!

**Comment by mirzap** [comment]
Implemented. You can use now with() method.

**Comment by azooziidev** [comment]
Many thanks!!!
